# params config
# iter params
batch_size:    2048
epoch:         32
learn_rate:    0.01
model_dir:     '../docs/model/'
model_name:    'best.h5'
# model_type:    'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable

# data prarms
title_dim:  0 # just placeholder
content_dim:  0 # just placeholder
embed_dim:  100
label:
  dim: 2
  loss_weight:    1 # not use now
  loss_activate:  'sigmoid' # only sigmoid, softmax
  loss_func:  'binary_crossentropy' # only binary_crossentropy, categorical_crossentropy
  W_regularizer: 0.1
  activity_reg: {l1: 0.1}
  batch_norm: {momentum: 0.9}
# layer params
Conv1D:
    layer1:
        filters:       128
        filter_size:   5
        padding_mode:   'valid'
        pooling_size:  3 # default 2
        dropout:       0.3
    layer2:
        filters:       256
        filter_size:   4
        padding_mode:   'valid'
        pooling_size:  2 # default 2
        dropout:      0.3
    layer3:
        filters:       256
        filter_size:   3
        padding_mode:   'valid'
        pooling_size:  3 # default 2
        dropout:      0.3
RNN:
    cell: 48
    dropout: 0.3  # default 0.
    recurrent_dropout: 0.3  # default 0.
